name: flutter_application_1
description: A new Flutter project.

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/portadas/
    - .env
